# Generated by Django 2.1.7 on 2019-03-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='age',
            field=models.PositiveIntegerField(verbose_name='年齡'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='politic',
            field=models.TextField(verbose_name='政見'),
        ),
    ]
